language: c

services:
    - docker

before_install:
    - docker pull redrifle/spectacle:latest
    - docker run -itd --name spectacle redrifle/eternity

script:
    - docker exec spectacle cmake -DBUILD_TESTING=ON -H/spectacle -B/build
    - docker exec spectacle cmake --build /build
    - docker exec spectacle cmake --build /build --target test
